---

- name: Download sample kubernetes data
  ansible.builtin.get_url:
    url: 'https://zinc-public-data.s3.us-west-2.amazonaws.com/zinc-enl/sample-k8s-logs/k8slog_json.json.zip'
    mode: '0400'
    dest: "{{ openobserve_home }}/k8slog_json.json.zip"
    owner: "{{ openobserve_user }}"
    checksum: sha256:6705fbf64df4ba42d1e78f9e7bb9673b454a71986efc84d855685d8874f1da5c

- name: Ensure unzip is present
  ansible.builtin.package:
    name: unzip
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Unarchive sample kubernetes data
  ansible.builtin.unarchive:
    src: "{{ openobserve_home }}/k8slog_json.json.zip"
    dest: "{{ openobserve_home }}"
    owner: "{{ openobserve_user }}"
    remote_src: true
    mode: '0644'

- name: Load sample data
  # FIXME! nok...
  ansible.builtin.uri:
    url: "http://localhost:5080/api/default/default/_json"
    method: POST
    body_format: json
    src: "{{ openobserve_home }}/k8slog_json.json"
    headers:
      Content-Type: application/x-www-form-urlencoded
    remote_src: true
    url_username: "{{ openobserve_root_user_email }}"
    url_password: "{{ openobserve_root_user_pass }}"
    return_content: yes
  register: _result
  until: _result.status == 200
  when: false

- name: Load sample data (curl)
  ansible.builtin.command:  # noqa command-instead-of-module no-changed-when
    cmd: curl http://localhost:5080/api/default/default/_json -i -u "{{ openobserve_root_user_email }}:{{ openobserve_root_user_pass }}"  -d "@{{ openobserve_home }}/k8slog_json.json"
