---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    openobserve_dashboards_url:
      - https://github.com/openobserve/dashboards/raw/refs/heads/main/OpenObserve/OpenObserve%20Internals.dashboard.json
      - https://github.com/openobserve/dashboards/raw/refs/heads/main/OpenObserve/OpenObserve%20Infrastructure.dashboard.json
      - https://github.com/openobserve/dashboards/raw/refs/heads/main/Usage/Usage%20_%20Overall.dashboard.json
      - https://github.com/openobserve/dashboards/raw/refs/heads/main/Usage/Usage%20_%20Org.dashboard.json
    openobserve_restore_enable: true
    openobserve_backup_config_enable: true
    ssl_dir: /etc/ssl/certs
    site_server_name: "{{ ansible_fqdn }}"
    openobserve_ca_bundle_filepath: "{{ hardenwebserver_ssl_cert | default(ssl_dir + '/' + site_server_name + '.crt') }}"
    # mkcert san
    alternate_dns: 'localhost 127.0.0.1 ::1'
    openobserve_backup_web_url: https://localhost
    openobserve_backup_config_tls_validate: false
    # search.py: why openobserve_web_url defaults ok but not those two?
    openobserve_root_user_email: root@example.com
    openobserve_root_user_pass: root@example.com
    # https://openobserve.ai/docs/ingestion/logs/filebeat/
    filebeat_version: 8.x
    filebeat_output_elasticsearch_enabled: true
    filebeat_output_elasticsearch_hosts:
      - "localhost:5080"
    filebeat_output_elasticsearch_auth:
      username: "{{ openobserve_root_user_email }}"
      password: "{{ openobserve_root_user_pass }}"
    filebeat_template: "{{ lookup('env','GITHUB_WORKSPACE') }}/juju4.openobserve/templates/filebeat-openobserve.yml.j2"
    filebeat_inputs:
      - type: log
        paths:
          - "/var/log/*.log"
    filebeat_output_logstash_enabled: false
    filebeat_enable_logging: true
    filebeat_log_dir: /var/log/filebeat
    filebeat_log_filename: filebeat.log
    hardenwebserver_disable_http: true
    hardenwebserver_cert: mkcert
    hardenwebserver_https_template: ../../templates/nginx.conf.j2
    # hardenwebserver_header_csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'report-sample'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:;base-uri 'none'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; report-uri /csp/report.php;"
    hardenwebserver_header_csp: "upgrade-insecure-requests; report-uri /csp/report.php;"
    # hardenwebserver_ssl_cert: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
    # hardenwebserver_ssl_key: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem"
    hardenwebserver_systemd_dir_acl:
      - { p: /etc/letsencrypt/archive, perm: rx, m: '0711' }
      - { p: /etc/letsencrypt/live, perm: rx, m: '0711' }
      - { p: "/etc/ssl/private", perm: rx, m: '0710' }
      - { p: "/var/log/nginx", perm: rwx, m: '0755' }
    hardenwebserver_systemd_files_acl:
      # - { p: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem", perm: r }
      - { p: "/etc/ssl/private/{{ ansible_fqdn }}.key", perm: r }
      - { p: "/etc/ssl/private/dhparam4.pem", perm: r }
    otelcol_auth_key: "{{ openobserve_root_user_email + ':' + openobserve_root_user_pass | ansible.builtin.b64encode }}"
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8)
  roles:
    - geerlingguy.filebeat
    # need certificate to exist before creating openobserve-backup.service
    # else service fails to start
    - juju4.harden_nginx
    - { role: juju4.openobserve, openobserve_deploy_type: 'server' }
    - { role: juju4.otelcol,
        openobserve_server_ansible_host: localhost,
        otelcol_server_url: "https://localhost/api/default/",
    }
  tasks:
    - name: Git clone python-openobserve
      ansible.builtin.git:
        repo: https://github.com/juju4/python-openobserve
        dest: /root/python-openobserve
        version: 181ef789ca248f2274cd89e44e6a3b12624f8955
    - name: Install python-openobserve
      ansible.builtin.pip:
        name: file:///root/python-openobserve
        virtualenv: /root/venv
    - name: Install pip dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        virtualenv: /root/venv
      loop:
        - pandas
        - python-dotenv
        - jmespath
        - pytest
    - name: Create .env file
      ansible.builtin.copy:
        content: |
          OO_HOST={{ openobserve_web_url }}
          OO_USER={{ openobserve_root_user_email }}
          OO_PASS={{ openobserve_root_user_pass }}
          {% if openobserve_ca_bundle_filepath != None and openobserve_ca_bundle_filepath | length > 0 %}
          REQUESTS_CA_BUNDLE={{ openobserve_ca_bundle_filepath }}
          {% endif %}
        dest: /root/.env
        mode: '0600'
        owner: root
    - name: Add search.py
      ansible.builtin.template:
        src: search.py.j2
        dest: /root/search.py
        mode: '0700'
        owner: root
    - name: Run search
      ansible.builtin.command:  # noqa no-changed-when
        cmd: /root/venv/bin/python search.py
      args:
        chdir: /root
    - name: Run pytest offline
      ansible.builtin.command:  # noqa no-changed-when
        cmd: /root/venv/bin/pytest test_openobserve_api_offline.py
      args:
        chdir: /root/python-openobserve/tests
      failed_when: false
    - name: Run pytest online
      ansible.builtin.command:  # noqa no-changed-when
        cmd: /root/venv/bin/pytest test_openobserve_api.py
      args:
        chdir: /root/python-openobserve/tests
      failed_when: false
    - name: Run config backup
      ansible.builtin.command:  # noqa no-changed-when
        cmd: /var/_openobserve_backup/venv/bin/python backup.py
      args:
        chdir: /var/_openobserve_backup/o2
      become: true
      become_user: _o2_backup
