---
name: API Fuzzing with Smugglefuzz

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  schemathesis-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.openobserve
      ANSIBLE_SUITE: default
      # Matching role defaults
      BASIC_AUTH: cm9vdEBleGFtcGxlLmNvbTpyb290QGV4YW1wbGUuY29t

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint jmespath
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Install OpenObserve
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Install Smugglefuzz
        run: |
          curl -O https://github.com/Moopinger/smugglefuzz/releases/download/v0.2.2/smugglefuzz_Linux_x86_64.tar.gz
          curl -O https://github.com/Moopinger/smugglefuzz/releases/download/v0.2.2/smugglefuzz_0.2.2_checksums.txt
          hash=$(sha256sum smugglefuzz_Linux_x86_64.tar.gz | awk '{ print $1 }')
          grep ${hash} smugglefuzz_*_checksums.txt
          tar xzf smugglefuzz_Linux_x86_64.tar.gz
          sudo install -m 0755 smufflefuzz /usr/local/bin/

      - name: Run Smugglefuzz tests
        run: |
          smugglefuzz scan --confirm http://localhost:5080
