---
name: API Fuzzing with Schemathesis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  schemathesis-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.openobserve
      ANSIBLE_SUITE: default
      # Matching role defaults
      BASIC_AUTH: cm9vdEBleGFtcGxlLmNvbTpyb290QGV4YW1wbGUuY29t

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint jmespath
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg

      - name: Install OpenObserve
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
          cd
          curl -O http://localhost:5080/api-doc/openapi.json
          ls -lA
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Install Schemathesis
        run: pip install schemathesis

      - name: Run Schemathesis tests
        run: |
          schemathesis run http://localhost:5080/api-doc/openapi.json \
            --url=http://localhost:5080 \
            --header "Authorization: Basic $BASIC_AUTH" \
            --checks all \
            --include-path org_id=default \
            --include-path stream_name=default \
            --include-path email_id=schemathesis@example.com

      - name: Upload Schemathesis results
        uses: actions/upload-artifact@v4
        with:
          name: schemathesis-results
          path: .
        if: failure()

      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@264fd875d3c6e1bf65da1f0a63e095cbe41ffef3  # tag=v1.5.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: openapi.json
          default-timeout: 20000
        if: ${{ always() }}
        continue-on-error: true
